import {walkingKeys} from './camera-control.mjs';
import {tunnelTool} from './mining-tools.mjs';
import {Vec3} from 'vec3';
const air=b=>b&&b.boundingBox==='empty'&&!['lava','fire','soul_fire','water'].includes(b.name);
export async function centerColumn(bot){const p=bot.entity.position.floored();const center=p.offset(.5,0,.5);bot.setControlState('sneak',true);for(let t=0;t<30;t++){const d=center.minus(bot.entity.position);if(Math.hypot(d.x,d.z)<.08)break;for(const [key,value] of Object.entries(walkingKeys(bot.entity.yaw,d.x,d.z)))bot.setControlState(key,value);await bot.waitForTicks(1);}bot.clearControlStates();await bot.waitForTicks(3);if(Math.hypot(center.x-bot.entity.position.x,center.z-bot.entity.position.z)>.15)throw Error('Could not center player before wall placement');}
export async function climbColumn(bot,top,log=()=>{}){bot.checkedTravelActive=true;try{
 bot.pathfinder.setGoal(null);bot.clearControlStates();await bot.waitForTicks(4);let climbed=0;
 while(bot.entity.position.y<top-.1&&climbed<(bot.columnLimit||4)){if(bot.emergencyTravelStop)throw Error('Breath interrupts column');const p=bot.entity.position.floored();if(!bot.entity.onGround)throw Error('Column ascent requires standing on solid ground');const ref=bot.blockAt(p.offset(0,-1,0));if(ref?.boundingBox!=='block')throw Error('No solid column foundation');
  await centerColumn(bot);
  const head=bot.blockAt(p.offset(0,2,0));if(!air(head)){if(!head?.diggable)throw Error('Column ceiling cannot be mined');for(const d of [[1,0,0],[-1,0,0],[0,1,0],[0,0,1],[0,0,-1]])if(bot.blockAt(head.position.offset(...d))?.name==='lava'){bot.columnLavaBlocked=true;throw Error('Lava beside column ceiling');}const pick=tunnelTool(bot,head);if(!pick)throw Error('No pickaxe for column ceiling');await bot.equip(pick,'hand');await bot.dig(head,true);await bot.waitForTicks(2);}
  const block=['cobblestone','dirt','netherrack','blackstone','polished_blackstone_bricks','cracked_polished_blackstone_bricks','basalt','polished_basalt','end_stone'].map(n=>bot.inventory.items().find(i=>i.name===n&&(n!=='cobblestone'||i.count>48))).find(Boolean);if(!block)throw Error('No column building material');bot.deactivateItem();await bot.equip(block,'hand');await bot.look(bot.entity.yaw,-Math.PI/2);bot.setControlState('jump',true);try{let raised=false;for(let n=0;n<12;n++){await bot.waitForTicks(1);if(bot.entity.position.y>p.y+1.02){raised=true;break;}}if(!raised)throw Error('Insufficient column jump clearance');await bot.waitForTicks(1);await bot._placeBlockWithOptions(ref,new Vec3(0,1,0),{forceLook:'ignore',swingArm:'right'});}finally{bot.setControlState('jump',false);}await bot.waitForTicks(9);if(bot.entity.position.y<p.y+.9||bot.blockAt(p)?.boundingBox!=='block')throw Error('Column step not confirmed');climbed++;log('column_step',{position:bot.entity.position,material:block.name});
 }return 'Climbed '+climbed+' checked column blocks';
}finally{bot.checkedTravelActive=false;bot.clearControlStates();}}
export async function descendColumn(bot,bottom,log=()=>{}){bot.checkedTravelActive=true;try{
 bot.pathfinder.setGoal(null);bot.clearControlStates();await bot.waitForTicks(3);let count=0;
 while(bot.entity.position.y>bottom+.1&&count<6){if(bot.emergencyTravelStop)throw Error('Breath interrupts descent');const p=bot.entity.position.floored(),floor=bot.blockAt(p.offset(0,-1,0));let below=bot.blockAt(p.offset(0,-2,0));if(bot.allowColumnFill&&floor?.boundingBox==='block'&&air(below)){const item=['end_stone','netherrack','blackstone','polished_blackstone_bricks','cracked_polished_blackstone_bricks','basalt','polished_basalt','cobblestone','dirt'].map(n=>bot.inventory.items().find(i=>i.name===n&&(n!=='cobblestone'||i.count>48))).find(Boolean);if(!item)throw Error('No material for lower landing');await bot.equip(item,'hand');await bot.placeBlock(floor,new Vec3(0,-1,0));await bot.waitForTicks(2);below=bot.blockAt(p.offset(0,-2,0));}if(!bot.entity.onGround||floor?.boundingBox!=='block'||below?.boundingBox!=='block')throw Error('Column descent has no checked landing');const tool=tunnelTool(bot,floor);if(!tool)throw Error('No tool for column descent');await bot.equip(tool,'hand');await bot.dig(floor,true);await bot.waitForTicks(9);if(Math.abs(bot.entity.position.y-(p.y-1))>.1)throw Error('Column descent did not land');count++;log('column_down_step',{position:bot.entity.position});}
 return 'Descended '+count+' checked column blocks';
}finally{bot.checkedTravelActive=false;bot.clearControlStates();}}
