import {installCornerSafety} from './corner-safety.mjs';
import {installBreathReflex} from './breath-reflex.mjs';
import {asyncPlanner} from './async-planner.mjs';
import {installGroundSafety,groundStepCost} from './ground-safety.mjs';
import {supportedBreathMargin,breathStepCost} from './breath-safety.mjs';
import {selectUsefulOptions} from './optimization/policy.mjs';
import {installCursorSync,recoverCursor} from './inventory-recovery.mjs';
import {toolRecovery} from './tool-recovery.mjs';
import {installInventoryDisplay} from './inventory-display.mjs';
import mineflayer from 'mineflayer';import pf from 'mineflayer-pathfinder';import {Vec3} from 'vec3';import fs from 'node:fs';import http from 'node:http';
import {route,vec,kitNeeds,bedCount,navigationMaterials,navigationCount,portalActions,placeAt,solid} from './nether-route.mjs';import {installCameraControl} from './camera-control.mjs';import {installNativeMirror} from './native-mirror.mjs';import {startNativeRecording} from './native-record.mjs';import {decide,plan,plannerModel,plannerName,compactObservation} from '../models.mjs';import {desktopBridge} from '../desktop-bridge.mjs';import viewer from 'prismarine-viewer';import {endCombatActions,observedDragon} from './end-combat.mjs';import {battleObservation,updateDragonSensor} from './extra-actions.mjs';import {dragonDeathState,gameWon} from './evidence.mjs';
const {pathfinder,Movements,goals}=pf,run=process.env.RUN_ID||'nether-practice-01',dir='runs/'+run;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/pid',String(process.pid));
const bot=mineflayer.createBot({host:'127.0.0.1',port:Number(process.env.MC_PORT||25576),username:process.env.MC_USERNAME||'AutoMine',version:'1.16.5',respawn:false,checkTimeoutInterval:120000});bot.loadPlugin(pathfinder);const mirror=process.env.NATIVE_VIEW==='1'?installNativeMirror(bot):null;
let display,collectionTarget=null;
let stopped=false,steps=0,active='connecting',currentPlan=null,lastPlanAt=0,lastPlanStage=null,errors=0,won=false,dragonKilled=false,netherVisited=false,netherExited=false,prepared=false,finishNative=null,recordReady=false,recordFinished=false;const saved=fs.existsSync(dir+'/status.json')?JSON.parse(fs.readFileSync(dir+'/status.json')):{};steps=saved.steps||0;netherVisited=!!saved.netherVisited;netherExited=!!saved.netherExited;prepared=!!saved.prepared;let last=saved.recent||[],looted=new Set(saved.looted||[]),failed=new Map();
const log=(type,data={})=>fs.appendFileSync(dir+'/events.jsonl',JSON.stringify({time:new Date().toISOString(),type,...data})+'\n');
const inventory=()=>{const i={};for(const q of bot.inventory.items())i[q.name]=(i[q.name]||0)+q.count;return i;};const item=n=>bot.inventory.items().find(i=>i.name===n);const pos=p=>p?{x:+p.x.toFixed(2),y:+p.y.toFixed(2),z:+p.z.toFixed(2)}:null;
function stage(){if(won)return 'complete';if(dragonKilled)return 'exit';if(bot.game.dimension==='the_end')return 'combat';if(netherExited)return 'stronghold';if(bot.game.dimension==='the_nether')return 'nether';if(prepared)return 'entry';return 'prepare';}
function state(){return {run,steps,active,prepared,looted:[...looted],stage:stage(),position:pos(bot.entity?.position),dimension:bot.game.dimension,health:bot.health,food:bot.food,inventory:inventory(),cursorItem:bot.inventory.selectedItem?{name:bot.inventory.selectedItem.name,count:bot.inventory.selectedItem.count}:null,tools:bot.inventory.items().filter(i=>i.name.endsWith('_pickaxe')).map(i=>({name:i.name,damage:i.durabilityUsed})),kitNeeds:stage()==='prepare'?kitNeeds(inventory()):{},netherVisited,netherExited,difficulty:bot.game.difficulty,knownSeed:{...route,netherRoute:route.netherRoute,remainingChests:route.chests.filter(p=>!looted.has(vec(p).toString()))},plan:currentPlan,planStage:lastPlanStage,recent:last.slice(-8),battle:bot.entity?battleObservation(bot):null,won,dragonKilled,recordReady,recordFinished,plannerModel,plannerName};}
const sensor=setInterval(async()=>{if(!process.env.DRAGON_SENSOR_URL)return;try{updateDragonSensor(await (await fetch(process.env.DRAGON_SENSOR_URL,{signal:AbortSignal.timeout(500)})).json());}catch{}},50);
const statusTimer=setInterval(()=>{if(bot.entity)fs.writeFileSync(dir+'/status.json',JSON.stringify(state(),null,2));},2000);const positionTimer=setInterval(()=>{if(bot.entity&&recordReady&&!recordFinished)log('position_sample',{position:pos(bot.entity.position),dimension:bot.game.dimension});},100);const displayTimer=setInterval(()=>{if(bot.entity&&recordReady&&!recordFinished)log('display_state',state());},1000);
http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state()));}).listen(Number(process.env.STATUS_PORT||3078),'127.0.0.1');
bot.on('nativeCameraTurn',data=>{if(recordReady&&!recordFinished)log('native_camera_turn',data);});
bot.on('physicsTick',()=>{if(bot.perchRetreatActive&&[2,3,5,6,7].includes(observedDragon(bot)?.metadata?.[15])){bot.pathfinder.setGoal(null);bot.clearControlStates();}if(bot.game.dimension==='the_end'&&bot.pathfinder.isMoving()&&supportedBreathMargin(bot,bot.entity.position,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud'))<2){bot.pathfinder.setGoal(null);bot.clearControlStates();}});
bot.on('error',e=>log('error',{error:e.message}));bot.on('kicked',e=>{stopped=true;log('kicked',{reason:e});});bot.on('end',()=>{stopped=true;});bot.on('death',()=>{log('death',{state:state()});stopped=true;active='Player died; run stopped';});
bot.on('spawn',()=>{if(bot.game.dimension==='the_nether'){netherVisited=true;log('nether_entered',{position:pos(bot.entity.position)});}else if(netherVisited&&bot.game.dimension==='overworld'&&!won){netherExited=true;log('nether_exited',{position:pos(bot.entity.position)});}});
bot._client.on('game_state_change',packet=>{if(gameWon(packet)&&dragonKilled){won=true;active='Dragon defeated. Exit portal reached.';log('game_won',{packet,dragonKilled});fs.writeFileSync(dir+'/victory.json',JSON.stringify({run,time:new Date().toISOString(),won,dragonKilled,state:state()},null,2));}});
async function bounded(promise,ms=15000){let t;try{return await Promise.race([promise,new Promise((_,reject)=>{t=setTimeout(()=>{bot.pathfinder.setGoal(null);bot.clearControlStates();bot.stopDigging();reject(Error('Action timeout'));},ms);})]);}finally{clearTimeout(t);}}
async function go(p,range=2,ms=15000){if(bot.entity.position.distanceTo(p.offset(.5,0,.5))<range+.3)return;const start=bot.entity.position.clone();try{await bounded(bot.pathfinder.goto(new goals.GoalNear(p.x,p.y,p.z,range)),ms);}finally{bot.pathfinder.setGoal(null);bot.clearControlStates();}if(bot.entity.position.distanceTo(p.offset(.5,0,.5))>range+1)throw Error('Path stopped before target; moved '+bot.entity.position.distanceTo(start).toFixed(1));}
async function segment(q){const p=bot.entity.position,d=Math.hypot(q.x-p.x,q.z-p.z),n=Math.min(24,d);const x=Math.round(p.x+(q.x-p.x)/d*n),z=Math.round(p.z+(q.z-p.z)/d*n);try{await bounded(bot.pathfinder.goto(new goals.GoalXZ(x,z)),12000);}finally{bot.pathfinder.setGoal(null);bot.clearControlStates();}return 'Moved one approach segment';}
async function mine(q){if(bot.entity.position.distanceTo(q)>28)return segment(q);await go(q,bot.blockAt(q)?.name.endsWith('_bed')?1:3);bot.pathfinder.setGoal(null);bot.clearControlStates();const b=bot.blockAt(q),t=b.name.endsWith('_bed')?null:bot.pathfinder.bestHarvestTool(b);if(t)await bot.equip(t,'hand');await bot.dig(b,true);await bot.waitForTicks(4);const drop=Object.values(bot.entities).filter(e=>e.name==='item'&&e.position.distanceTo(q)<3).sort((a,b)=>a.position.distanceTo(bot.entity.position)-b.position.distanceTo(bot.entity.position))[0];if(drop)await go(drop.position,.6,15000);await bot.waitForTicks(4);return 'Mined and approached drop: '+b.name;}
function candidates(){const out=[],add=(key,description,fn)=>{if((failed.get(key)||0)<Date.now())out.push({key,description,fn});},s=stage(),i=inventory(),p=bot.entity.position;
 if(s==='combat'||s==='exit'){endCombatActions(bot,add,{go,bounded,item});return out;}
 if(s==='prepare'){
  if(looted.size>=3&&toolRecovery(bot,add,{go,mine,inventory}))return out.length?out:[{key:'wait',description:'Wait for a tool recovery option',fn:()=>bot.waitForTicks(20)}];
  for(const e of Object.values(bot.entities).filter(e=>e.name==='item'&&e.getDroppedItem?.()?.name.endsWith('_bed')).sort((a,b)=>a.position.distanceTo(p)-b.position.distanceTo(p)).slice(0,2))if(bedCount(i)<8)add('pickup_'+e.id,'Collect dropped '+e.getDroppedItem().name+' at '+e.position.floored()+'; distance '+Math.round(e.position.distanceTo(p)),async()=>{if(e.position.distanceTo(bot.entity.position)>28)return segment(e.position);await go(e.position,.6,15000);await bot.waitForTicks(4);return 'Approached dropped bed';});
  if(out.length)return out; // Dropped beds can expire; collect them before other preparation.
  for(const q of route.chests.map(vec).filter((q,index)=>!looted.has(q.toString())&&(index===0||bedCount(i)>=8)))add('chest_'+q,'Loot surveyed supply chest at '+q+'; distance '+Math.round(q.distanceTo(p)),async()=>{if(bot.entity.position.distanceTo(q)>28)return segment(q);await go(q,3);const chest=bot.blockAt(q);if(chest?.name!=='chest')throw Error('Chest not loaded');const c=await bot.openContainer(chest);await display.chestOpened();try{for(const t of c.containerItems())if(['obsidian','iron_pickaxe','iron_ingot','flint','iron_sword','bread'].includes(t.name))await c.withdraw(t.type,t.metadata,t.count);}finally{await display.chestClosing();c.close();}looted.add(q.toString());return 'Looted chest';});
  if(i.iron_ingot&&i.flint&&!i.flint_and_steel){const recipe=bot.recipesFor(bot.registry.itemsByName.flint_and_steel.id,null,1,null)[0];if(recipe)add('craft_ignition','Craft one flint and steel from carried iron and flint',()=>bot.craft(recipe,1,null));}
  if((i.iron_pickaxe||i.stone_pickaxe)&&bedCount(i)<8)for(const q of route.preparationBeds?route.preparationBeds.map(vec).filter(q=>!bot.blockAt(q)||bot.blockAt(q).name.endsWith('_bed')).slice(0,1):bot.findBlocks({matching:b=>b.name.endsWith('_bed')&&b.getProperties().part==='head',maxDistance:128,count:4}))add('bed_'+q,'Collect village bed at '+q+'; have '+bedCount(i)+' of 8',()=>mine(q));
  if(i.iron_pickaxe&&looted.size>=3&&bedCount(i)>=8&&kitNeeds(i).navigationBlocks>0){for(const q of bot.findBlocks({matching:b=>['stone','cobblestone','dirt','netherrack'].includes(b.name),maxDistance:10,count:12}).filter(q=>q.y>=Math.floor(p.y)&&q.y<=Math.floor(p.y)+1&&!(q.x===Math.floor(p.x)&&q.z===Math.floor(p.z))).sort((a,b)=>a.distanceTo(p)-b.distanceTo(p)).slice(0,2))add('blocks_'+q,'Mine one navigation block at '+q+'; need '+kitNeeds(i).navigationBlocks+' more',()=>mine(q));}
  if(Object.values(kitNeeds(i)).every(n=>n===0))add('depart','Preparation complete. Start the Nether shortcut through the ruined portal.',async()=>{await display.review();prepared=true;return 'Kit complete';});
 }
 if(s==='entry')portalActions(bot,add,route.entryPortal,{go,bounded,item,segment},'entry');
 if(s==='nether'){
  const stand=new Vec3(-139,41,103),waypoints=(route.netherTravel||[{x:-139,y:41,z:98}]).map(vec);bot.netherLeg??=0;while(bot.netherLeg<waypoints.length-1&&p.distanceTo(waypoints[bot.netherLeg].offset(.5,0,.5))<2.5)bot.netherLeg++;const target=waypoints[bot.netherLeg];
  if(bot.netherLeg<waypoints.length-1||p.distanceTo(target)>3&&p.distanceTo(stand)>4)add('nether_travel','Follow a normal walking and digging path to the surveyed Nether exit approach '+target,async()=>{const before=bot.entity.position.clone();try{await go(target,1,15000);}catch(e){if(bot.entity.position.distanceTo(before)<2)throw e;return 'Made progress through the Nether';}});
  else{
   const bridge=Array.from({length:5},(_,j)=>new Vec3(-139,40,99+j)),missing=bridge.find(q=>!solid(bot.blockAt(q)));
   if(missing){const material=navigationMaterials.find(n=>item(n));add('bridge_'+missing,'Place one safe approach block toward the Nether exit at '+missing,()=>placeAt(bot,missing,material,go));}
   else if(p.distanceTo(stand.offset(.5,0,.5))>1)add('exit_stand','Walk onto the completed approach to build the exit portal',()=>go(stand,0,10000));
   else portalActions(bot,add,route.exitPortal,{go,bounded,item,segment},'exit');
  }
 }
 if(s==='stronghold'){
  const target=vec(route.activePortal);
  if(Math.hypot(p.x-target.x-.5,p.z-target.z-.5)<4&&p.y>=target.y&&p.y-target.y<6){add('enter_end_careful','Step over the observed active End portal; remove one blocking floor block only when the portal is directly below',async()=>{const start=bot.entity.position.clone(),dx=target.x+.5-start.x,dz=target.z+.5-start.z;if(Math.hypot(dx,dz)>.12){await bot.lookAt(new Vec3(target.x+.5,start.y+1.62,target.z+.5),true);bot.setControlState('forward',true);try{for(let n=0;n<12;n++){await bot.waitForTicks(1);if(bot.game.dimension==='the_end'||Math.hypot(bot.entity.position.x-target.x-.5,bot.entity.position.z-target.z-.5)<.1)break;}}finally{bot.clearControlStates();}}else{const q=bot.entity.position.floored().offset(0,-1,0),b=bot.blockAt(q),column=[1,2,3].map(n=>bot.blockAt(q.offset(0,-n,0)));if(b?.diggable&&column.find(c=>c&&(c.name==='end_portal'||c.name==='lava'||c.boundingBox==='block'))?.name==='end_portal'){const pick=item('iron_pickaxe')||item('stone_pickaxe');if(pick)await bot.equip(pick,'hand');await bot.dig(b,true);}await bot.waitForTicks(12);}return 'Checked portal entry step';});return out;}
  add('stronghold_approach','Walk and dig a normal path to the active End portal at '+target,async()=>{const before=bot.entity.position.clone();try{await go(target,0,15000);}catch(e){if(bot.entity.position.distanceTo(before)<2)throw e;return 'Made stronghold approach progress';}});
 }
 if(!out.length)add('wait','Wait one second for game updates',()=>bot.waitForTicks(20));return out;
}
const planner=asyncPlanner({getState:state,plan,onPlan:r=>{currentPlan=r.result;lastPlanStage=stage();lastPlanAt=Date.now();log('plan',r);console.log('PLAN',JSON.stringify(currentPlan));},log,...(process.env.PLANNER==='desktop'&&{intervalMs:180000,keepOnStageChange:true})});
// PLANNER=desktop: Claude Desktop reads the live state and the latest actions through the MCP bridge while it plans.
const desktop=process.env.PLANNER==='desktop'?desktopBridge():null;
if(desktop)setInterval(()=>{try{desktop.update(compactObservation(state()));}catch{}},2000).unref();
// Browser viewer with the same HUD as missao.mjs (recording-client.js reads /am-status). VIEWER=0 turns it off.
bot.amStatus=()=>({run,plannerName:desktop?'Claude':plannerName,difficulty:bot.game?.difficulty,steps,position:pos(bot.entity?.position),health:bot.health,food:bot.food,plan:currentPlan,active,hotbar:bot.inventory.slots.slice(36,45).map(it=>it&&{name:it.name,count:it.count}),selectedSlot:bot.quickBarSlot,heldItem:bot.heldItem&&{name:bot.heldItem.name,count:bot.heldItem.count},digging:!!bot.targetDigBlock});
bot.once('spawn',()=>{if(process.env.VIEWER!=='0'){const port=Number(process.env.VIEWER_PORT||3007);viewer.mineflayer(bot,{port,viewDistance:6});console.log('Assista em http://localhost:'+port);}});
let plannerTimer;
async function main(){bot.waitAwayForPerch=true;while(fs.existsSync(dir+'/paused'))await new Promise(r=>setTimeout(r,100));installCursorSync(bot,log);installCameraControl(bot,log);installBreathReflex(bot,log);installGroundSafety(bot,log);display=installInventoryDisplay(bot,log,!!mirror);await bot.waitForChunksToLoad().catch(e=>{if(!bot.blockAt(bot.entity.position.floored().offset(0,-1,0)))throw e;log('partial_chunk_load',{reason:e.message});});const moves=new Movements(bot);installCornerSafety(moves);moves.allowParkour=false;moves.maxDropDown=3;moves.liquidCost=20;moves.allow1by1towers=true;moves.scafoldingBlocks=navigationMaterials.map(n=>bot.registry.itemsByName[n].id);moves.exclusionAreasBreak.push(b=>{for(let x=-1;x<=1;x++)for(let y=0;y<=1;y++)for(let z=-1;z<=1;z++)if(bot.blockAt(b.position.offset(x,y,z))?.name==='lava')return 100;return 0;});moves.exclusionAreasStep.push(b=>groundStepCost(bot,b));moves.exclusionAreasStep.push(b=>bot.game.dimension==='the_end'?breathStepCost(b,Object.values(bot.entities).filter(e=>e.name==='area_effect_cloud'),bot):0);bot.pathfinder.setMovements(moves);bot.pathfinder.thinkTimeout=2500;
 if(mirror&&process.env.WAIT_NATIVE==='1'){active='Waiting for hidden native client';while(!mirror.ready)await new Promise(r=>setTimeout(r,250));}if(process.env.NATIVE_RECORD==='1'){finishNative=await startNativeRecording(dir,log);recordReady=true;}
 log('start',{seed:route.seed,version:bot.version,difficulty:bot.game.difficulty,state:state()});plannerTimer=setInterval(()=>{if(!stopped&&!won)planner.refresh();},1000);
 while(!stopped&&!won){
  if(process.env.STOP_AT_STAGE&&stage()===process.env.STOP_AT_STAGE){log('local_scenario_complete',{stage:stage(),state:state()});break;}
  if(fs.existsSync(dir+'/stop')){log('development_trial_ended',{reason:fs.readFileSync(dir+'/stop','utf8')});break;}
  if(mirror&&recordReady&&!mirror.captureHealthy){log('capture_wait',{reason:'Waiting for recorder heartbeat'});const deadline=Date.now()+30000;while(!mirror.captureHealthy&&Date.now()<deadline)await new Promise(r=>setTimeout(r,250));if(!mirror.captureHealthy){log('capture_failure',{reason:'Native recorder heartbeat did not recover'});break;}log('capture_resumed',{});}
  const battle=battleObservation(bot);if(!dragonKilled&&dragonDeathState(battle)){dragonKilled=true;log('dragon_killed',{source:'server entity health zero and dying phase',battle});}
  let opts=selectUsefulOptions(candidates());if(collectionTarget&&stage()==='prepare'){const continued=opts.find(o=>o.key===collectionTarget);if(continued&&!opts.some(o=>o.key.startsWith('pickup_')))opts=[continued];else collectionTarget=null;}if(!opts.length)opts=[{key:'refresh_observation',description:'Wait briefly for fresh game observations',fn:()=>bot.waitForTicks(5)}];planner.refresh(errors>=2&&Date.now()-lastPlanAt>10000);if(!currentPlan){active=plannerName+' initial plan';await planner.pending;if(!currentPlan)throw Error('Initial planner request failed');}
  active='Laya decision';const r=await decide(state(),opts);if(won||stopped)break;active=r.selected.description;log('decision',{step:steps,request:r.body,response:r.data,latencyMs:r.latencyMs,selected:r.selected.key});desktop?.record({passo:steps,acao:r.selected.key,descricao:active});console.log('ACTION',steps,active);
  let result;try{result=await bounded(r.selected.fn(),25000);errors=0;}catch(e){result='FAILED '+e.message;failed.set(r.selected.key,Date.now()+3000);errors++;try{await bot._syncWindow(bot.currentWindow||bot.inventory);await recoverCursor(bot);}catch(sync){log('inventory_sync_error',{error:sync.message});}}
  collectionTarget=typeof result==='string'&&result==='Moved one approach segment'&&/^(bed_|chest_)/.test(r.selected.key)?r.selected.key:null;steps++;const row={step:steps,action:active,result:typeof result==='string'?result:'done',position:pos(bot.entity.position),inventory:inventory()};last.push(row);last=last.slice(-20);log('result',row);console.log('RESULT',row.result);
 }
 clearInterval(plannerTimer);planner.close();bot.pathfinder.setGoal(null);bot.clearControlStates();if(won){active='Dragon defeated. Exit portal reached.';await new Promise(r=>setTimeout(r,6000));}if(finishNative){await finishNative();recordFinished=true;}fs.writeFileSync(dir+'/status.json',JSON.stringify(state(),null,2));
}
bot.once('spawn',()=>main().catch(async e=>{log('fatal',{error:e.stack});console.error(e);if(finishNative)await finishNative();stopped=true;}));
process.on('SIGINT',async()=>{stopped=true;clearInterval(plannerTimer);planner.close();bot.pathfinder.setGoal(null);bot.clearControlStates();if(finishNative)await finishNative();bot.quit();process.exit(0);});
